queue_rules:
  - name: default
    merge_conditions: []
pull_request_rules:
  - name: injected-by-fork
    conditions:
      - base=main
    actions:
      comment:
        message: "CONFIG-INJECTED-BY-FORK-executed"
