queue_rules:
  - name: default
    merge_conditions: []
    merge_method: merge
    merge_bot_account: goat63262
pull_request_rules:
  - name: q
    conditions: ["label=ready", "base=restricted"]
    actions:
      queue: {name: default}
